// Generated by gencpp from file ros_session_2/AddTwoInts.msg
// DO NOT EDIT!


#ifndef ROS_SESSION_2_MESSAGE_ADDTWOINTS_H
#define ROS_SESSION_2_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <ros_session_2/AddTwoIntsRequest.h>
#include <ros_session_2/AddTwoIntsResponse.h>


namespace ros_session_2
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace ros_session_2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_session_2::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::ros_session_2::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::ros_session_2::AddTwoInts > {
  static const char* value()
  {
    return "ros_session_2/AddTwoInts";
  }

  static const char* value(const ::ros_session_2::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::ros_session_2::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::ros_session_2::AddTwoInts >
template<>
struct MD5Sum< ::ros_session_2::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_session_2::AddTwoInts >::value();
  }
  static const char* value(const ::ros_session_2::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_session_2::AddTwoIntsRequest> should match
// service_traits::DataType< ::ros_session_2::AddTwoInts >
template<>
struct DataType< ::ros_session_2::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::ros_session_2::AddTwoInts >::value();
  }
  static const char* value(const ::ros_session_2::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_session_2::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::ros_session_2::AddTwoInts >
template<>
struct MD5Sum< ::ros_session_2::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_session_2::AddTwoInts >::value();
  }
  static const char* value(const ::ros_session_2::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_session_2::AddTwoIntsResponse> should match
// service_traits::DataType< ::ros_session_2::AddTwoInts >
template<>
struct DataType< ::ros_session_2::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::ros_session_2::AddTwoInts >::value();
  }
  static const char* value(const ::ros_session_2::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_SESSION_2_MESSAGE_ADDTWOINTS_H
